// Code generated by goctl. DO NOT EDIT.
package types

type HelloworldReq struct {
	Msg string `form:"msg":"msg"`
}

type HelloworldResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
